// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApIl5eDtbYUuTqFtQ6ZD-6egruQXoOsjw',
    appId: '1:835252374882:web:41e49b4884ae636b34f03b',
    messagingSenderId: '835252374882',
    projectId: 'shopbase-732af',
    authDomain: 'shopbase-732af.firebaseapp.com',
    storageBucket: 'shopbase-732af.appspot.com',
    measurementId: 'G-5YVG5MYGC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOfKulhs2tVyBVP6sJyQY9ErgrpZr-mc',
    appId: '1:835252374882:android:43a7c1c40b8ade2a34f03b',
    messagingSenderId: '835252374882',
    projectId: 'shopbase-732af',
    storageBucket: 'shopbase-732af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ZkMhAR8PhqKI4IpehBoeDQbAORWFkt0',
    appId: '1:835252374882:ios:5f73aee8c079235f34f03b',
    messagingSenderId: '835252374882',
    projectId: 'shopbase-732af',
    storageBucket: 'shopbase-732af.appspot.com',
    iosBundleId: 'com.example.shopbaseFirebase',
  );
}
